name: azkar
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.29+31

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  google_mobile_ads: ^5.3.1
  http: ^1.3.0
  youtube_explode_dart: ^2.3.6
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.5.1
  just_audio: ^0.9.45
  flutter_localization: ^0.3.1
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  connectivity_plus: ^6.1.2
  url_launcher: ^6.3.1
  user_messaging_platform: ^1.3.0
  firebase_in_app_messaging: ^0.8.1+4
  geolocator: ^13.0.2
  adhan: ^2.0.0+1
  permission_handler: ^11.4.0
  font_awesome_flutter: ^10.8.0
  xml: ^6.5.0
  share_plus: ^11.0.0
  wallpaper_manager_flutter: ^0.0.2
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  get_it: ^7.6.7
  injectable: ^2.4.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true

  # إضافة ملفات الأصول (assets) للقراءة: النصوص والصوتيات
  assets:
    - assets/texts/
    - assets/audio/
    - assets/ramadan_reminder.mp3

  # إضافة الخطوط المخصصة (Fonts)
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
